- l10n/de_CH.php
similar to https://github.com/owncloud/core/issues/11274
> remove obsolete langs. #11274

- README.md
@Raydiation FYI
@DeepDiver1975 Please enable Scrutinizer on this repository.
> Be the new fancy guy maintaining this app

- css/notes.css
Please test @fossxplorer @sanneterpstra @beli3ver @LukasReschke @JanMalte @hermanthe
@MarvAmBass thank you for the solution – next time you can just submit a pull request yourself. ;)
> fix shrinked text area height, fix #77, thanks to @MarvAmBass

- appinfo/app.php
- controller/errors.php
- controller/notesapicontroller.php
- controller/notescontroller.php
- controller/pagecontroller.php
- db/entity.php
- db/note.php
> Fix PHPDoc and some other code style issues

- appinfo/info.xml
Please review @LukasReschke @Henni @Raydiation
> fix info.xml max version so it's installable on core master

- css/notes.css
It’s not really done in other ownCloud apps (in News it’s at least a tad useful to separate the articles, but not here). Please review @Henni @Raydiation @LukasReschke :)
> remove gradient from app-content

- templates/main.php
This removes imports of libs removed in e58384be9f8bdbd30c935d16734006deb4f3f6c6
> Remove unused imports

- css/notes.css
- templates/note.php
Remove unused styles and clean up the remaining rules.
This reduces the size of notes.css from 263 lines to 98 lines.
> Cleanup css

- css/notes.css
depends on #146 
cc @pierrejochem @stefan-niedermann
> Add horizontal line styling

- css/notes.css
This PR lines up headings, lists and quotes to the left.
fixes #136 
depends on #146
> Hanging punctuation

- templates/main.php
> Remove tooltip.css

- README.md
@jancborchardt @LukasReschke @BernhardPosselt if that's alright with you
> Add myself as maintainer

- css/vendor/bootstrap/tooltip.css
- templates/main.php
this fixes the tooltips in owncloud 8.1
fixes #165 
please review @BernhardPosselt
> Revert the removal of tooltip.css

- .travis.yml
- appinfo/info.xml
> notes is running on 9.0 as well

- css/notes.css
Please review @Henni @LukasReschke @owncloud/designers
> reduce opacity of delete action to distract less

- css/notes.css
This is what i meant in #173 :-)
> fix shown scrollbar on empty pages

- css/notes.css
Just some text styling details, please review @owncloud/designers @Henni @BernhardPosselt @LukasReschke
> heading style details, improve vertical rhythm

- appinfo/info.xml
Ref: https://github.com/owncloud/notes/issues/185#issuecomment-168397292
> Fix requiremin metadata

- js/app/directives/timeoutchange.js
This should fix the issue of the save function not firing up when pasting
#179
> Fix for #179

- appinfo/info.xml
Please review @Henni @LukasReschke 
Otherwise it is not installable on dev setups.
> update info.xml, add @Henni, up max-version

- service/notesservice.php
https://github.com/owncloud/notes/issues/187
> #187 Fix multibyte filename generation

- service/notesservice.php
> Remove debug log

- README.md
Inform the people that this old repository has been moved to Nextcloud.
@Henni @LukasReschke Please review/merge.
> We have moved to Nextcloud

- README.md
> Revert "We have moved to Nextcloud"

- CHANGELOG.md
- appinfo/info.xml
Wait for https://github.com/owncloud/notes/pull/280
> Release 2.0.4

- .drone.yml
- README.md
- phpunit.integration.xml
- phpunit.xml
@PVince81 please add codecov_token to the drone repo https://drone.owncloud.com/owncloud/notes/settings/secrets
Then we can rerun CI here, and all will be green.
Issue #298
> Implement codecov

- composer.lock
- phpunit.xml
- tests/integration/controller/NotesApiControllerTest.php
- tests/integration/controller/NotesControllerTest.php
- tests/unit/controller/NotesApiControllerTest.php
- tests/unit/controller/NotesControllerTest.php
- tests/unit/controller/PageControllerTest.php
- tests/unit/db/NoteTest.php
- tests/unit/service/NotesServiceTest.php
1) Adjust PHPUnit Framework namespace for PHPUnit6 
2) phpunit enable failOnRisky failOnWarning 
3) remove unused use statements 
4) Updating bamarni/composer-bin-plugin (v1.2.0 => v1.3.0)
> Phpunit 5 6

- .drone.starlark
- composer.json
- composer.lock
- phpunit.xml
- tests/integration/controller/NotesApiControllerTest.php
- tests/integration/controller/NotesControllerTest.php
- tests/unit/controller/NotesApiControllerTest.php
- tests/unit/controller/NotesControllerTest.php
- tests/unit/controller/PageControllerTest.php
- tests/unit/service/NotesServiceTest.php
Similar to https://github.com/owncloud/configreport/pull/121
> Adjust tests

- .drone.starlark
- tests/unit/service/NotesServiceTest.php
- vendor-bin/owncloud-codestyle/composer.json
like done in core https://github.com/owncloud/core/pull/36580
and apply latest drone starlark code changes
Note: there was no effect here on `.drone.yml`
> Coding standard 2.0.0

- phpunit.xml
- tests/unit/service/NotesServiceTest.php
Fixes https://github.com/owncloud/notes/issues/407
> [tests-only] Adjust php unit tests to ensure compatibility with PHPUnit v9.5

- .drone.star
- composer.json
- composer.lock
- controller/pagecontroller.php
- phpstan.neon
- vendor-bin/owncloud-codestyle/composer.json
- vendor-bin/phpstan/composer.json
- update `.drone.star` with current CI code from activity app
- update tool dependencies
- update coding-standard to v4 and apply to the code
> [full-ci] CI changes

- .drone.star
- remove the use of `drone_token`
- adjust the use of the `cache_s3` tokens to use the names now available
Part of issue https://github.com/owncloud/QA/issues/818
> [CI][full-ci]Update drone file
